version: '3.7'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=automation
      - DOCKER_INFLUXDB_INIT_PASSWORD=automation123
      - DOCKER_INFLUXDB_INIT_ORG=automationOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=automationBucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=automationToken

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:
