name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, safari]
        mobileDevice: [android, ios]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: |
          mvn test -Dbrowser=${{ matrix.browser }} -DmobileDevice=${{ matrix.mobileDevice }}

      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.browser }}-${{ matrix.mobileDevice }}
          path: target/surefire-reports/
